### ISSUE TITLE
Consider removing `cgmath` dependency

### ISSUE THREAD

**Issue by LukasKalbertodt** [omarkmu/winconsole#3]
Hi there!

I just compiled a command line application (`cargo-sweep`) and wondered why it would need to compile `rand` and all its sub crates. Investigating this lead to the following dependency chain: `cargo-sweep -> colored -> winconsole -> cgmath -> rand`. The last step (`cgmath` requiring `rand`) I already knew about and reported it [here](https://github.com/rustgd/cgmath/issues/481). In the next `cgmath` release, `rand` is probably only an optional dependency. But until then, `cgmath` sadly pulls in several `rand` crates, which are not used in most cases.

I skimmed the code in this repo and saw that it only uses `cgmath::Vector2` (and apparently not even many methods of it?). In that case it would be fairly easy to quickly write a small `Vector2` type in this crate.

I know that this "hand coding instead of dependency" is really not nice and in a perfect world, perfect code reuse is possible without overhead. But as I see it, it could be beneficial to remove `cgmath` as dependency.

**Comment by omarkmu** [comment]
That's a good point; I believe I initially added cgmath as a dependency to play nice with other crates which use Vector2, but I could always make it optional and include conversions. I'll get on that, thanks.

**Comment by omarkmu** [comment]
Removed the dependency in 46f6d80. I'll work on adding more to it along with the optional dependency soon.

**Comment by omarkmu** [comment]
Resolved in bf47611c598d367657ed8a25e95f2f99f2101ce5.
